### ISSUE TITLE
Error when install locally

### ISSUE THREAD

**Issue by diorz38** [syncfusion/ej2-showcase-js-expensetracker#13]
step: 
- clone reop
- npm install
- gulp serve

error:
```
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (D:\ej2-showcase-js-expensetracker-master\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\ej2-showcase-js-expensetracker-master\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\ej2-showcase-js-expensetracker-master\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by SharonSanchez** [comment]
Hi Dior,

The above error occurs when using a lower gulp version when compared with the node version. In order to resolve this, please try by downgrading your node version.

Else attach this file to the cloned application and then proceed with the commands npm install and gulp serve.

https://www.syncfusion.com/downloads/support/directtrac/general/ze/npm-shrinkwrap1856772240

Please feel free to reach out to us if you have any concerns.
